name: "Mypycify & Build Python Wheel"
description: "Build & cache a wheel for a mypyc C-extension, upload artifact for use, and optionally commit/PR non-.gitignored build files."
icon: package
color: blue
inputs:
  hash-key:
    description: "File globs (YAML list of strings) to include in the hash key for caching. This input is required."
    required: true
  python-version:
    description: "Python version to use (passed to actions/setup-python)"
    required: true
  pip-cache-dependency-path:
    description: "Dependency files for actions/setup-python pip cache. This input is passed directly to the 'cache-dependency-path' parameter of actions/setup-python."
    required: false
    default: ""
  ccache:
    description: "Enable ccache for C/C++ compilation (Linux/macOS only). Default: false."
    required: false
    default: "false"
  push-source:
    description: "Enable auto-commit and push or PR of changes if build output changes."
    required: false
    default: "false"
  commit-message:
    description: "Commit message to use when committing changes."
    required: false
    default: "chore: compile C files for source control"
  normalize-source:
    description: "Enable normalization of C files for diffchecking."
    required: false
    default: "false"
  trigger-pr-number:
    description: "Optional: PR number of the triggering PR (e.g., 1234). If set, the PR body will include 'Triggered by #<number>'."
    required: false
    default: ""
  trigger-branch-name:
    description: "Optional: Name of the triggering branch (e.g., feature/my-feature). Used in PR body if trigger-pr-number is not set."
    required: false
    default: ""
  build-command:
    description: "Custom build command to run (default: 'python -m build --wheel'). If you use a custom command, you are responsible for ensuring all requirements are installed before mypycify or as part of the build command."
    required: false
    default: "python -m build --wheel"
outputs:
  artifact-name:
    description: "The name of the uploaded wheel artifact."
runs:
  using: "composite"
  steps:
    - name: Validate inputs
      if: inputs.normalize-source == 'true' && inputs.push-source != 'true'
      run: |
        echo "ERROR: normalize-source cannot be true unless push-source is also true."
        exit 1
      shell: bash

    - name: Compute hash key
      id: hash_key
      run: echo "hash-key=${{ hashFiles(inputs.hash-key) }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Compute unique artifact key
      id: artifact_key
      shell: bash
      run: |
        ARTIFACT_KEY="${{ runner.os }}-py${{ inputs.python-version }}-${{ steps.hash_key.outputs.hash-key }}"
        echo "artifact-key=$ARTIFACT_KEY" >> $GITHUB_OUTPUT

    - name: Cache built wheel (dist/)
      id: wheel-cache
      uses: actions/cache@v4
      with:
        path: dist/
        key: ${{ steps.artifact_key.outputs.artifact-key }}

    - name: Set up Python
      if: steps.wheel-cache.outputs.cache-hit != 'true'
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: ${{ inputs.pip-cache-dependency-path }}

    - name: Compute ccache restore-key prefix
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel-cache.outputs.cache-hit != 'true'
      id: ccache_restore_key
      shell: bash
      run: |
        RESTORE_KEY="BobTheBuidler/mypycify:ccache-data-${{ runner.os }}-${{ inputs.python-version }}"
        echo "restore-key=$RESTORE_KEY" >> $GITHUB_OUTPUT

    - name: Compute ccache key
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel-cache.outputs.cache-hit != 'true'
      id: ccache_key
      shell: bash
      run: |
        CCACHE_KEY="${{ steps.ccache_restore_key.outputs.restore-key }}-${{ steps.hash_key.outputs.hash-key }}"
        echo "ccache-key=$CCACHE_KEY" >> $GITHUB_OUTPUT

    - name: Compute mypy cache restore-key prefix
      id: mypy_cache_restore_key
      if: steps.wheel-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        MYPY_CACHE_PREFIX="BobTheBuidler/mypycify:mypy_cache-${{ runner.os }}-py${{ inputs.python-version }}"
        echo "restore-key=$MYPY_CACHE_PREFIX" >> $GITHUB_OUTPUT

    - name: Restore mypy cache
      id: mypy_cache_restore
      if: steps.wheel-cache.outputs.cache-hit != 'true'
      uses: actions/cache/restore@v4
      with:
        path: .mypy_cache
        key: ${{ steps.mypy_cache_restore_key.outputs.restore-key }}-${{ steps.hash_key.outputs.hash-key }}
        restore-keys: ${{ steps.mypy_cache_restore_key.outputs.restore-key }}

    - name: Set ccache-dir variable
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel-cache.outputs.cache-hit != 'true'
      run: |
        if [ "$RUNNER_OS" = "Linux" ]; then
          echo "CCACHE_DIR=$HOME/.cache/ccache" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" = "macOS" ]; then
          echo "CCACHE_DIR=$HOME/Library/Caches/ccache" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Install ccache on Linux
      if: inputs.ccache == 'true' && steps.wheel-cache.outputs.cache-hit != 'true' && runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y ccache
      shell: bash
    - name: Install ccache on macOS
      if: inputs.ccache == 'true' && steps.wheel-cache.outputs.cache-hit != 'true' && runner.os == 'macOS'
      run: brew install ccache
      shell: bash

    - name: Restore ccache cache
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel-cache.outputs.cache-hit != 'true'
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ steps.ccache_key.outputs.ccache-key }}
        restore-keys: ${{ steps.ccache_restore_key.outputs.restore-key }}

    - name: Show ccache config before build
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel-cache.outputs.cache-hit != 'true'
      run: |
        echo "ccache -- version && ccache -p"
        echo "==================== CCACHE CONFIG (BEFORE BUILD) ============================"
        ccache --version && ccache -p
        echo "============================================================================="
      shell: bash

    - name: Show ccache stats before build
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel-cache.outputs.cache-hit != 'true'
      run: |
        echo "ccache -s"
        echo "==================== CCACHE STATS (BEFORE BUILD) ============================="
        ccache -s
        echo "============================================================================="
      shell: bash

    - name: Install build dependencies
      if: steps.wheel-cache.outputs.cache-hit != 'true' && inputs.build-command == 'python -m build --wheel'
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
      shell: bash

    - name: Build wheel (with ccache)
      if: inputs.ccache == 'true' && steps.wheel-cache.outputs.cache-hit != 'true'
      env:
        CC: ccache gcc
      run: |
        echo "Running build command: ${{ inputs.build-command }}"
        eval "${{ inputs.build-command }}"
      shell: bash

    - name: Build wheel (without ccache)
      if: inputs.ccache != 'true' && steps.wheel-cache.outputs.cache-hit != 'true'
      run: |
        echo "Running build command: ${{ inputs.build-command }}"
        eval "${{ inputs.build-command }}"
      shell: bash

    - name: Show ccache stats after build
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel-cache.outputs.cache-hit != 'true'
      run: |
        echo "ccache -s"
        echo "==================== CCACHE STATS (AFTER BUILD) =============================="
        ccache -s
        echo "============================================================================="
      shell: bash

    - name: Save ccache cache
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ steps.ccache_key.outputs.ccache-key }}

    - name: Save mypy cache
      id: mypy_cache_save
      uses: actions/cache/save@v4
      with:
        path: .mypy_cache
        key: ${{ steps.mypy_cache_restore_key.outputs.restore-key }}-${{ steps.hash_key.outputs.hash-key }}

    - name: Compute unique artifact name
      id: artifact_name
      shell: bash
      run: |
        ARTIFACT_NAME="BobTheBuidler_mypycified_wheel-${{ steps.artifact_key.outputs.artifact-key }}"
        echo "artifact-name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v5
      with:
        name: ${{ steps.artifact_name.outputs.artifact-name }}
        path: dist/*.whl

    - name: Normalize C files for diffchecking
      if: inputs.normalize-source == 'true'
      run: |
        for f in build/*.c; do
          if ! grep -q 'DIFFCHECK_PLACEHOLDER' "$f"; then
            sed -i '1i#ifndef DIFFCHECK_PLACEHOLDER\n#define DIFFCHECK_PLACEHOLDER 0\n#endif' "$f"
          fi
        done
        sed -i 's/\(CPy_AddTraceback([^,]*, *[^,]*, *\)[0-9]\+\(, *[^)]*)\)/\1DIFFCHECK_PLACEHOLDER\2/g' build/*.c
        sed -i 's/CPyStatics\[[0-9]\+\]/CPyStatics[DIFFCHECK_PLACEHOLDER]/g' build/*.c
      shell: bash

    - name: Check for changes
      id: check_changes
      run: |
        git add .
        if git diff --cached --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Check if branch still exists on remote
      if: inputs.push-source == 'true' && steps.check_changes.outputs.changed == 'true'
      id: branch_exists
      shell: bash
      run: |
        BRANCH_NAME="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
        if git ls-remote --exit-code --heads origin "$BRANCH_NAME"; then
          echo "branch_exists=true" >> $GITHUB_OUTPUT
        else
          echo "branch_exists=false" >> $GITHUB_OUTPUT
          echo "The branch $BRANCH_NAME no longer exists on GitHub. Exiting gracefully (xfail-at-checkout=true)."
          exit 0
        fi

    # Only allow direct commit if this is a push event to a branch in the main repository and branch still exists.
    - name: Commit and push changes (if possible)
      if: inputs.push-source == 'true' && steps.check_changes.outputs.changed == 'true' && github.event_name == 'push' && steps.branch_exists.outputs.branch_exists == 'true'
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "${{ inputs.commit-message }}"
        git push
      shell: bash

    # Otherwise, create a PR for changes if branch still exists.
    - name: Create Pull Request
      if: inputs.push-source == 'true' && steps.check_changes.outputs.changed == 'true' && github.event_name != 'push' && steps.branch_exists.outputs.branch_exists == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        branch: auto/update-mypycify
        base: ${{ github.head_ref || github.ref_name }}
        title: ${{ inputs.commit-message }}
        body: |
          This PR updates build artifacts based on the latest implementation. Generated by GitHub Actions.
          ${{ inputs.trigger-pr-number && format('Triggered by #{0}', inputs.trigger-pr-number) || (inputs.trigger-branch-name && format('Triggered by branch: {0}', inputs.trigger-branch-name) || '') }}
        commit-message: ${{ inputs.commit-message }}
        delete-branch: true
